chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.home, name='home'),
    path('enter_room/', views.enter_room, name='enter_room'),
    path('<str:room_name>/<str:username>/', views.room, name='room'),
    path('send/', views.SaveMessages.as_view(), name='save_messages'),
    path('get_room_messages/', views.GetMessages.as_view(), name='get_messages'),
    path('private_chat/', views.private_chat, name='private_chat'),
    path('private/<str:sender>/<str:receiver>/', views.private, name='private'),
    path('save_private/', views.SavePrivate.as_view(), name='save_private'),
    path('get_private_messages/', views.GetPrivate.as_view(), name='get_private_messages'),
]

my_chats/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.user_login, name='login'),
    path('chat/', include('chat.urls', namespace='chat')),
    path('users/', include('users.urls', namespace='users'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('add_country/', views.add_country, name='add_country'),
    path('add_city/', views.add_city, name='add_city'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('create_profile/', views.user_profile, name='create_profile')
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models


class Room(models.Model):
    name = models.CharField(max_length=1000)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Room'
        verbose_name_plural = 'Rooms'

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'
        ordering = ['-date']

    def __str__(self):
        return f'{self.user} in room {self.room}'


class PrivateChat(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Private Chat'
        verbose_name_plural = 'Private Chats'
        ordering = ['-date']

    def __str__(self):
        return f'sender:{self.sender}, receiver:{self.receiver}'

chat/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View
from .models import Room, Message, PrivateChat


# homepage
@login_required
def home(request):
    all_users = User.objects.all
    all_rooms = Room.objects.all()
    if request.method == 'POST':
        room_username = request.user.username
        user_room_name = request.POST['room_name']
        room_name = user_room_name.lower()
        username = room_username.lower()

        if Room.objects.filter(name=room_name).exists():
            return redirect('/chat/'+room_name+'/'+username+'?chat room name='+room_name+' '+'username='+username)
        else:
            new_room = Room.objects.create(name=room_name, created_by=request.user)
            new_room.save()
            return redirect('/chat/'+room_name+'/'+username+'?chat room name='+room_name+' '+'username='+username)
    context = {
        'all_users': all_users,
        'all_rooms': all_rooms
    }
    return render(request, 'chat/home.html', context)


def enter_room(request):
    if request.method == 'POST':
        room_username = request.user.username
        user_room_name = request.POST['select_room']
        room_name = user_room_name.lower()
        username = room_username.lower()
        return redirect('/chat/'+room_name+'/'+username+'?chat room name='+room_name+' '+'username='+username)


def room(request, room_name, username):
    room_details = Room.objects.filter(name=room_name)
    context = {
        'room_name': room_name,
        'room_details': room_details,
        'username': username
    }
    return render(request, 'chat/room.html', context)


class GetMessages(LoginRequiredMixin, View):
    def get(self, request):
        room_name = request.GET.get('room_name')
        room_msg = Message.objects.filter(room__name=room_name)[:30]
        messages = []
        data = {}
        for i in range(len(room_msg)):
            x = room_msg[i].date
            datex = x.strftime("%d-%m-%Y")
            timex = x.strftime("%H:%M:%S %p")
            date_sent = datex+' '+'at'+' '+timex

            msg = {
                'id': room_msg[i].id,
                'user': room_msg[i].user.username,
                'room_name': room_msg[i].room.name,
                'message': room_msg[i].message,
                'date': date_sent,
            }
            messages.append(msg)
        data['message_details'] = messages
        return JsonResponse(data)


class SaveMessages(LoginRequiredMixin, View):
    def get(self, request):
        username = request.GET.get('username', None)
        room_id = request.GET.get('room_id', None)
        message = request.GET.get('message', None)

        chat_room = Room.objects.get(id=room_id)
        obj = Message.objects.create(
            user=request.user,
            room=chat_room,
            message=message,
        )
        message_details = {
            'id': obj.id,
            'user': request.user.username,
            'room_name': obj.room.name,
            'room_creator': chat_room.created_by,
            'message': obj.message,
            'date': obj.date
        }
        data = {
            'message_details': message_details
        }
        return JsonResponse(data)


def private_chat(request):
    sender_x = request.user.username
    receiver_x = request.POST['receiver']
    sender = sender_x.lower()
    receiver = receiver_x.lower()
    if sender == receiver:
        messages.error(request, 'You cannot chat with yourself')
        return redirect('chat:home')
    return redirect('/chat/private/'+sender+'/'+receiver+'?private chat between '+sender+'and '+receiver)


def private(request, sender, receiver):
    chat_details = PrivateChat.objects.filter(sender__username=sender, receiver__username=receiver)
    context = {
        'sender': sender,
        'receiver': receiver,
        'chat_details': chat_details
    }
    return render(request, 'chat/private_chat.html', context)


class SavePrivate(LoginRequiredMixin, View):
    def get(self, request):
        sender = request.GET.get('sender', None)
        user_rec = request.GET.get('receiver', None)
        message = request.GET.get('message', None)
        receiver = User.objects.get(username=user_rec)

        obj = PrivateChat.objects.create(
            sender=request.user,
            receiver=receiver,
            message=message
        )
        private_msg = {
            'id': obj.id,
            'sender': request.user.username,
            'receiver': user_rec,
            'message': obj.message,
            'date': obj.date
        }
        data = {
            'private_msg': private_msg
        }
        return JsonResponse(data)


class GetPrivate(View):
    def get(self, request):
        sender = request.GET.get('sender', None)
        receiver = request.GET.get('receiver', None)
        messages = []
        data = {}
        user_sender = User.objects.get(username=sender)
        user_receiver = User.objects.get(username=receiver)
        if PrivateChat.objects.filter(sender__username=user_sender, receiver__username=user_receiver).exists():
            pri_msg = PrivateChat.objects.filter(sender__username=user_sender, receiver__username=user_receiver)[:30]

            for i in range(len(pri_msg)):
                x = pri_msg[i].date
                datex = x.strftime("%d-%m-%Y")
                timex = x.strftime("%H:%M:%S %p")
                date_sent = datex + ' ' + 'at' + ' ' + timex

                msg = {
                    'id': pri_msg[i].id,
                    'message': pri_msg[i].message,
                    'date': date_sent,
                    'sender': sender,
                    'receiver': receiver
                }
                messages.append(msg)
        if PrivateChat.objects.filter(sender__username=user_receiver, receiver__username=user_sender).exists():
            pri_msg = PrivateChat.objects.filter(sender__username=user_receiver, receiver__username=user_sender)[:30]
            for i in range(len(pri_msg)):
                x = pri_msg[i].date
                datex = x.strftime("%d-%m-%Y")
                timex = x.strftime("%H:%M:%S %p")
                date_sent = datex + ' ' + 'at' + ' ' + timex

                msg = {
                    'id': pri_msg[i].id,
                    'message': pri_msg[i].message,
                    'date': date_sent,
                    'sender': sender,
                    'receiver': receiver
                }
                messages.append(msg)
        data['private_details'] = messages
        return JsonResponse(data)

chat/templates/chat/home.html
{% extends 'users/base.html' %}

{% block title %}Chat | Home{% endblock title %}

{% block content %}
    <div class="form-group">
        <button class="form-submit" type="submit"><a href="{% url 'users:logout' %}">LogOut</a></button><br>
    </div>
    <h2>Hi {{ request.user.username }}!, Welcome to chat page</h2>
    <div class="message">
        {% if messages %}
            {% for message in messages %}
                <h3 style="text-align: center;">{{ message }}</h3>
            {% endfor %}
        {% endif %}
    </div>

    <div class="signup-content" id="group_chat">
        <form method="POST" id="signup-form" class="signup-form" action="{% url 'chat:enter_room' %}">
            {% csrf_token %}
            <h2 class="form-title">Select A Room To Enter:</h2>

            <div class="select_option">
                <span class="select-wrapper">
                    <select name="select_room">
                        <option value="*" disabled selected>Please select...</option>
                        {% for room in all_rooms %}
                            <option value="{{ room.name }}">{{ room.name }}</option>
                        {% endfor %}
                    </select>
                </span>
            </div>

            <div class="form-group">
                <input type="submit" name="submit" id="submit" class="form-submit" value="Enter Room"/>
            </div>
        </form>

        <h2>OR:</h2>

        <form method="POST" id="signup-form" class="signup-form">
            {% csrf_token %}
            <h2 class="form-title">Create a room and enter:</h2>
            <div class="form-group">
                <input type="text" class="form-input" name="room_name" id="room_name" placeholder="Create A Room" required/>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" name="submit" id="submit" class="form-submit" value="Create room and enter"/>
            </div>
        </form>
    </div>
    <br>

    <div class="signup-content">
        <div id="private_chat">
        <h2>Chat Privately with someone:</h2>
        <form method="POST" action="{% url 'chat:private_chat' %}" id="signup-form" class="signup-form">
            {% csrf_token %}
            <h3 class="form-title">Recipient's Username:</h3>

            <div class="select_option">
                <span class="select-wrapper">
                    <select name="receiver">
                        <option value="*" disabled selected>Select Users...</option>
                        {% for user in all_users %}
                            <option value="{{ user.username }}">{{ user.username }}</option>
                        {% endfor %}
                    </select>
                </span>
            </div>
            <div class="form-group">
                <input type="submit" name="submit" id="submit" class="form-submit" value="Start Private Chat"/>
            </div>
        </form>

        <h2>OR:</h2>
        <p>Type the username of the person you wish to chat with, using small letters</p>
        <form method="POST" action="{% url 'chat:private_chat' %}" id="signup-form" class="signup-form">
            {% csrf_token %}
            <h3>Recipient's Username:</h3>

            <div class="form-group">
                <input type="text" class="form-input" name="receiver" id="receiver" placeholder="Enter someone's username in small letters" required/>
            </div>
            <br>

            <div class="form-group">
                <input type="submit" name="submit" id="submit" class="form-submit" value="Start Private Chat"/>
            </div>
        </form>
    </div>
    </div>
{% endblock content%}

chat/templates/chat/private_chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Private Chat Page</title>
</head>
<body>
    <div>
        <h3>Chat Page between {{ sender }} and {{ receiver }}.</h3>
        <div id="display_chats">

        </div>
        <form id="private_form">
            {% csrf_token %}
            <input type="hidden" name="sender" id="sender" value="{{ sender }}" readonly><br>
            <input type="hidden" name="receiver" id="receiver" value="{{ receiver }}" readonly><br>
            {% for chat in chat_details %}
                <input type="hidden" name="chat_id" id="chat_id" value="{{ chat.id }}" readonly>
            {% endfor %}<br>
            <textarea id="message" name="message" required></textarea><br>
            <button type="submit">Send Chat</button>
        </form>
    </div>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'js/private_chat.js' %}"></script>
</body>
</html>

chat/templates/chat/room.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Room</title>
</head>
<body>
    <div>
        <h2>Chat Room - {{room_name}}</h2>
    </div>
    <div>
        <div>
            <h2>{{ username }} chat page</h2>
        </div>
        <div id="display_chats">

        </div>
        <input type="hidden" name="room_name" value="{{ room_name }}">
        <form id="post_form">
            {% csrf_token %}
            <input type="hidden" name="username" id="username" value="{{ username }}" readonly><br>
            {% for room in room_details %}
                <input type="hidden" name="room_id" id="room_id" value="{{ room.id }}" readonly>
            {% endfor %}<br>
            <textarea id="message" name="message" required></textarea><br>
            <button type="submit">Send Chat</button>
        </form>
    </div>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'js/room.js' %}"></script>
</body>
</html>