chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.home, name='home'),
    path('enter_room/', views.enter_room, name='enter_room'),
    path('<str:room_name>/<str:username>/', views.room, name='room'),
    path('send/', views.SaveMessages.as_view(), name='save_messages'),
    path('get_room_messages/', views.GetMessages.as_view(), name='get_messages'),
    path('private_chat/', views.private_chat, name='private_chat'),
    path('private/<str:sender>/<str:receiver>/', views.private, name='private'),
    path('save_private/', views.SavePrivate.as_view(), name='save_private'),
    path('get_private_messages/', views.GetPrivate.as_view(), name='get_private_messages'),
]

my_chats/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.user_login, name='login'),
    path('chat/', include('chat.urls', namespace='chat')),
    path('users/', include('users.urls', namespace='users'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('add_country/', views.add_country, name='add_country'),
    path('add_city/', views.add_city, name='add_city'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('create_profile/', views.user_profile, name='create_profile')
]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Profile, City


def forbidden_users(value):
    check_users = ['admin', 'css', 'js', 'authenticate', 'login', 'logout', 'administrator', 'root', 'email', 'user',
                   'join', 'sql', 'static', 'python', 'delete', 'sex', 'sexy']
    if value.lower() in check_users:
        raise ValidationError('Invalid name for user, this is a reserverd word.')


def invalid_user(value):
    if '@' in value or '+' in value or '-' in value or ':' in value:
        raise ValidationError('This is an Invalid user, Do not user these chars: @ , - , +, :')


def unique_email(value):
    if User.objects.filter(email__iexact=value).exists():
        raise ValidationError('User with this email already exists.')


def unique_user(value):
    if User.objects.filter(username__iexact=value).exists():
        raise ValidationError('User with this username already exists.')


class SignupForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={}), max_length=30, required=True, )
    email = forms.CharField(widget=forms.EmailInput(attrs={}), max_length=100, required=True, )
    password = forms.CharField(widget=forms.PasswordInput(attrs={}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={}), required=True,
                                       label="Confirm your password.")

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields['username'].validators.append(forbidden_users)
        self.fields['username'].validators.append(invalid_user)
        self.fields['username'].validators.append(unique_user)
        self.fields['email'].validators.append(unique_email)

    def clean(self):
        super(SignupForm, self).clean()
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if password != confirm_password:
            self._errors['password'] = self.error_class(['Passwords do not match. Try again'])
        return self.cleaned_data


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter Your Username'}), required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter Your Password'}), required=True)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'gender', 'date_of_birth', 'country', 'city', 'address',
                  'phone_number', 'profile_picture', 'interest', 'about_me']
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'Enter Your First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Enter Your Last Name'}),
            'date_of_birth': forms.TextInput(attrs={'placeholder': 'YYYY-MM-DD'}),
            'address': forms.TextInput(attrs={'placeholder': 'Enter Your Address'}),
            'phone_number': forms.TextInput(attrs={'placeholder': 'Enter Your Phone Number'}),
            'interest': forms.TextInput(attrs={'placeholder': 'What Topic(s) attract(s) You?'}),
            'about_me': forms.Textarea(attrs={'placeholder': 'Few Things About You...'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

users/views.py
import re
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SignupForm, LoginForm, ProfileForm
from .models import Country, City, Profile

all_countries = [
    ['AW', 'Aruba'],
    ['AF', 'Afghanistan'],
    ['AO', 'Angola'],
    ['AI', 'Anguilla'],
    ['AX', 'Åland Islands'],
    ['AL', 'Albania'],
    ['AD', 'Andorra'],
    ['AE', 'United Arab Emirates'],
    ['AR', 'Argentina'],
    ['AM', 'Armenia'],
    ['AS', 'American Samoa'],
    ['AQ', 'Antarctica'],
    ['TF', 'French Southern Territories'],
    ['AG', 'Antigua and Barbuda'],
    ['AU', 'Australia'],
    ['AT', 'Austria'],
    ['AZ', 'Azerbaijan'],
    ['BI', 'Burundi'],
    ['BE', 'Belgium'],
    ['BJ', 'Benin'],
    ['BQ', 'Bonaire, Sint Eustatius and Saba'],
    ['BF', 'Burkina Faso'],
    ['BD', 'Bangladesh'],
    ['BG', 'Bulgaria'],
    ['BH', 'Bahrain'],
    ['BS', 'Bahamas'],
    ['BA', 'Bosnia and Herzegovina'],
    ['BL', 'Saint Barthélemy'],
    ['BY', 'Belarus'],
    ['BZ', 'Belize'],
    ['BM', 'Bermuda'],
    ['BO', 'Bolivia, Plurinational State of'],
    ['BR', 'Brazil'],
    ['BB', 'Barbados'],
    ['BN', 'Brunei Darussalam'],
    ['BT', 'Bhutan'],
    ['BV', 'Bouvet Island'],
    ['BW', 'Botswana'],
    ['CF', 'Central African Republic'],
    ['CA', 'Canada'],
    ['CC', 'Cocos (Keeling) Islands'],
    ['CH', 'Switzerland'],
    ['CL', 'Chile'],
    ['CN', 'China'],
    ['CI', "Côte d'Ivoire"],
    ['CM', 'Cameroon'],
    ['CD', 'Congo, The Democratic Republic of the'],
    ['CG', 'Congo'],
    ['CK', 'Cook Islands'],
    ['CO', 'Colombia'],
    ['KM', 'Comoros'],
    ['CV', 'Cabo Verde'],
    ['CR', 'Costa Rica'],
    ['CU', 'Cuba'],
    ['CW', 'Curaçao'],
    ['CX', 'Christmas Island'],
    ['KY', 'Cayman Islands'],
    ['CY', 'Cyprus'],
    ['CZ', 'Czechia'],
    ['DE', 'Germany'],
    ['DJ', 'Djibouti'],
    ['DM', 'Dominica'],
    ['DK', 'Denmark'],
    ['DO', 'Dominican Republic'],
    ['DZ', 'Algeria'],
    ['EC', 'Ecuador'],
    ['EG', 'Egypt'],
    ['ER', 'Eritrea'],
    ['EH', 'Western Sahara'],
    ['ES', 'Spain'],
    ['EE', 'Estonia'],
    ['ET', 'Ethiopia'],
    ['FI', 'Finland'],
    ['FJ', 'Fiji'],
    ['FK', 'Falkland Islands (Malvinas)'],
    ['FR', 'France'],
    ['FO', 'Faroe Islands'],
    ['FM', 'Micronesia, Federated States of'],
    ['GA', 'Gabon'],
    ['GB', 'United Kingdom'],
    ['GE', 'Georgia'],
    ['GG', 'Guernsey'],
    ['GH', 'Ghana'],
    ['GI', 'Gibraltar'],
    ['GN', 'Guinea'],
    ['GP', 'Guadeloupe'],
    ['GM', 'Gambia'],
    ['GW', 'Guinea-Bissau'],
    ['GQ', 'Equatorial Guinea'],
    ['GR', 'Greece'],
    ['GD', 'Grenada'],
    ['GL', 'Greenland'],
    ['GT', 'Guatemala'],
    ['GF', 'French Guiana'],
    ['GU', 'Guam'],
    ['GY', 'Guyana'],
    ['HK', 'Hong Kong'],
    ['HM', 'Heard Island and McDonald Islands'],
    ['HN', 'Honduras'],
    ['HR', 'Croatia'],
    ['HT', 'Haiti'],
    ['HU', 'Hungary'],
    ['ID', 'Indonesia'],
    ['IM', 'Isle of Man'],
    ['IN', 'India'],
    ['IO', 'British Indian Ocean Territory'],
    ['IE', 'Ireland'],
    ['IR', 'Iran, Islamic Republic of'],
    ['IQ', 'Iraq'],
    ['IS', 'Iceland'],
    ['IL', 'Israel'],
    ['IT', 'Italy'],
    ['JM', 'Jamaica'],
    ['JE', 'Jersey'],
    ['JO', 'Jordan'],
    ['JP', 'Japan'],
    ['KZ', 'Kazakhstan'],
    ['KE', 'Kenya'],
    ['KG', 'Kyrgyzstan'],
    ['KH', 'Cambodia'],
    ['KI', 'Kiribati'],
    ['KN', 'Saint Kitts and Nevis'],
    ['KR', 'Korea, Republic of'],
    ['KW', 'Kuwait'],
    ['LA', "Lao People's Democratic Republic"],
    ['LB', 'Lebanon'],
    ['LR', 'Liberia'],
    ['LY', 'Libya'],
    ['LC', 'Saint Lucia'],
    ['LI', 'Liechtenstein'],
    ['LK', 'Sri Lanka'],
    ['LS', 'Lesotho'],
    ['LT', 'Lithuania'],
    ['LU', 'Luxembourg'],
    ['LV', 'Latvia'],
    ['MO', 'Macao'],
    ['MF', 'Saint Martin (French part)'],
    ['MA', 'Morocco'],
    ['MC', 'Monaco'],
    ['MD', 'Moldova, Republic of'],
    ['MG', 'Madagascar'],
    ['MV', 'Maldives'],
    ['MX', 'Mexico'],
    ['MH', 'Marshall Islands'],
    ['MK', 'North Macedonia'],
    ['ML', 'Mali'],
    ['MT', 'Malta'],
    ['MM', 'Myanmar'],
    ['ME', 'Montenegro'],
    ['MN', 'Mongolia'],
    ['MP', 'Northern Mariana Islands'],
    ['MZ', 'Mozambique'],
    ['MR', 'Mauritania'],
    ['MS', 'Montserrat'],
    ['MQ', 'Martinique'],
    ['MU', 'Mauritius'],
    ['MW', 'Malawi'],
    ['MY', 'Malaysia'],
    ['YT', 'Mayotte'],
    ['NA', 'Namibia'],
    ['NC', 'New Caledonia'],
    ['NE', 'Niger'],
    ['NF', 'Norfolk Island'],
    ['NG', 'Nigeria'],
    ['NI', 'Nicaragua'],
    ['NU', 'Niue'],
    ['NL', 'Netherlands'],
    ['NO', 'Norway'],
    ['NP', 'Nepal'],
    ['NR', 'Nauru'],
    ['NZ', 'New Zealand'],
    ['OM', 'Oman'],
    ['PK', 'Pakistan'],
    ['PA', 'Panama'],
    ['PN', 'Pitcairn'],
    ['PE', 'Peru'],
    ['PH', 'Philippines'], ['PW', 'Palau'], ['PG', 'Papua New Guinea'], ['PL', 'Poland'], ['PR', 'Puerto Rico'],
    ['KP', "Korea, Democratic People's Republic of"], ['PT', 'Portugal'], ['PY', 'Paraguay'],
    ['PS', 'Palestine, State of'], ['PF', 'French Polynesia'], ['QA', 'Qatar'], ['RE', 'Réunion'],
    ['RO', 'Romania'], ['RU', 'Russian Federation'], ['RW', 'Rwanda'], ['SA', 'Saudi Arabia'], ['SD', 'Sudan'],
    ['SN', 'Senegal'], ['SG', 'Singapore'], ['GS', 'South Georgia and the South Sandwich Islands'],
    ['SH', 'Saint Helena, Ascension and Tristan da Cunha'], ['SJ', 'Svalbard and Jan Mayen'],
    ['SB', 'Solomon Islands'], ['SL', 'Sierra Leone'], ['SV', 'El Salvador'], ['SM', 'San Marino'],
    ['SO', 'Somalia'], ['PM', 'Saint Pierre and Miquelon'], ['RS', 'Serbia'], ['SS', 'South Sudan'],
    ['ST', 'Sao Tome and Principe'], ['SR', 'Suriname'], ['SK', 'Slovakia'], ['SI', 'Slovenia'], ['SE', 'Sweden'],
    ['SZ', 'Eswatini'], ['SX', 'Sint Maarten (Dutch part)'], ['SC', 'Seychelles'], ['SY', 'Syrian Arab Republic'],
    ['TC', 'Turks and Caicos Islands'], ['TD', 'Chad'], ['TG', 'Togo'], ['TH', 'Thailand'], ['TJ', 'Tajikistan'],
    ['TK', 'Tokelau'], ['TM', 'Turkmenistan'], ['TL', 'Timor-Leste'], ['TO', 'Tonga'],
    ['TT', 'Trinidad and Tobago'], ['TN', 'Tunisia'], ['TR', 'Turkey'], ['TV', 'Tuvalu'],
    ['TW', 'Taiwan, Province of China'], ['TZ', 'Tanzania, United Republic of'], ['UG', 'Uganda'],
    ['UA', 'Ukraine'], ['UM', 'United States Minor Outlying Islands'], ['UY', 'Uruguay'], ['US', 'United States'],
    ['UZ', 'Uzbekistan'], ['VA', 'Holy See (Vatican City State)'], ['VC', 'Saint Vincent and the Grenadines'],
    ['VE', 'Venezuela, Bolivarian Republic of'], ['VG', 'Virgin Islands, British'], ['VI', 'Virgin Islands, U.S.'],
    ['VN', 'Viet Nam'], ['VU', 'Vanuatu'], ['WF', 'Wallis and Futuna'], ['WS', 'Samoa'], ['YE', 'Yemen'],
    ['ZA', 'South Africa'], ['ZM', 'Zambia'], ['ZW', 'Zimbabwe']]

all_states = [
    [['AF', 'Ghaznī'], ['AF', 'Sar-e Pul'], ['AF', 'Ghōr'], ['AF', 'Takhār'], ['AF', 'Helmand'], ['AF', 'Uruzgān'],
     ['AF', 'Herāt'], ['AF', 'Wardak'], ['AF', 'Jowzjān'], ['AF', 'Zābul'], ['AF', 'Kābul'], ['AF', 'Kandahār'],
     ['AF', 'Kāpīsā'], ['AF', 'Kunduz'], ['AF', 'Khōst'], ['AF', 'Kunar'], ['AF', 'Laghmān'], ['AF', 'Lōgar'],
     ['AF', 'Nangarhār'], ['AF', 'Balkh'], ['AF', 'Nīmrōz'], ['AF', 'Bāmyān'], ['AF', 'Nūristān'],
     ['AF', 'Bādghīs'], ['AF', 'Panjshayr'], ['AF', 'Badakhshān'], ['AF', 'Parwān'], ['AF', 'Baghlān'],
     ['AF', 'Paktiyā'], ['AF', 'Dāykundī'], ['AF', 'Paktīkā'], ['AF', 'Farāh'], ['AF', 'Samangān'],
     ['AF', 'Fāryāb']],

    [['AO', 'Benguela'], ['AO', 'Cuanza Sul'], ['AO', 'Zaire'], ['AO', 'Bié'], ['AO', 'Luanda'], ['AO', 'Huambo'],
     ['AO', 'Uíge'], ['AO', 'Cabinda'], ['AO', 'Malange'], ['AO', 'Namibe'], ['AO', 'Huíla'],
     ['AO', 'Cuando-Cubango'], ['AO', 'Moxico'], ['AO', 'Lunda Norte'], ['AO', 'Cunene'], ['AO', 'Bengo'],
     ['AO', 'Lunda Sul'], ['AO', 'Cuanza Norte']],

    [['AL', 'Librazhd'], ['AL', 'Dibër'], ['AL', 'Lezhë'], ['AL', 'Shkodër'], ['AL', 'Lushnjë'], ['AL', 'Tiranë'],
     ['AL', 'Mallakastër'], ['AL', 'Vlorë'], ['AL', 'Malësi e Madhe'], ['AL', 'Berat'], ['AL', 'Mirditë'],
     ['AL', 'Bulqizë'], ['AL', 'Dibër'], ['AL', 'Mat'], ['AL', 'Delvinë'], ['AL', 'Durrës'], ['AL', 'Pogradec'],
     ['AL', 'Devoll'], ['AL', 'Peqin'], ['AL', 'Elbasan'], ['AL', 'Përmet'], ['AL', 'Kolonjë'], ['AL', 'Pukë'],
     ['AL', 'Fier'], ['AL', 'Shkodër'], ['AL', 'Gjirokastër'], ['AL', 'Skrapar'], ['AL', 'Gramsh'],
     ['AL', 'Sarandë'], ['AL', 'Berat'], ['AL', 'Has'], ['AL', 'Tepelenë'], ['AL', 'Durrës'], ['AL', 'Kavajë'],
     ['AL', 'Tropojë'], ['AL', 'Elbasan'], ['AL', 'Kurbin'], ['AL', 'Tiranë'], ['AL', 'Fier'], ['AL', 'Kuçovë'],
     ['AL', 'Vlorë'], ['AL', 'Gjirokastër'], ['AL', 'Korçë'], ['AL', 'Korçë'], ['AL', 'Krujë'], ['AL', 'Kukës'],
     ['AL', 'Kukës'], ['AL', 'Lezhë']],

    [['AD', 'Escaldes-Engordany'], ['AD', 'La Massana'], ['AD', 'Ordino'], ['AD', 'Canillo'],
     ['AD', 'Sant Julià de Lòria'], ['AD', 'Encamp'], ['AD', 'Andorra la Vella']],

    [['AE', 'Ra’s al Khaymah'], ['AE', 'Ash Shāriqah'], ['AE', "'Ajmān"], ['AE', 'Umm al Qaywayn'],
     ['AE', 'Abū Ȥaby [Abu Dhabi]'], ['AE', 'Dubayy'], ['AE', 'Al Fujayrah']],

    [['AR', 'Santa Fe'], ['AR', 'Tucuman'], ['AR', 'Chubut'], ['AR', 'Tierra del Fuego'], ['AR', 'Corrientes'],
     ['AR', 'Cordoba'], ['AR', 'Jujuy'], ['AR', 'Salta'], ['AR', 'Santa Cruz'], ['AR', 'Buenos Aires'],
     ['AR', 'Ciudad Autónoma de Buenos Aires'], ['AR', 'San Luis'], ['AR', 'Entre Rios'],
     ['AR', 'Santiago del Estero'], ['AR', 'Chaco'], ['AR', 'San Juan'], ['AR', 'Catamarca'], ['AR', 'La Pampa'],
     ['AR', 'Mendoza'], ['AR', 'Misiones'], ['AR', 'Formosa'], ['AR', 'Neuquen'], ['AR', 'Rio Negro']],

    [['AM', 'Armavir'], ['AM', 'Sirak'], ['AM', "Syunik'"], ['AM', 'Erevan'], ['AM', 'Tavus'], ['AM', 'Aragacotn'],

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,500;1,500&display=swap" rel="stylesheet">
    <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Main css -->
</head>
<body>

    <div class="main">
        <section class="signup">
            <div class="container">
                {% block content %}
                {% endblock content %}
            </div>
        </section>
    </div>

    <!-- JS -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block javascript %}
    {% endblock javascript %}
</body>
</html>

users/templates/users/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

users/templates/users/create_profile.html
{% extends 'users/base.html' %}

{% block title %}Create Profile Form{% endblock title %}

{% block content %}
    <div class="message">
        {% if messages %}
            {% for message in messages %}
                <h3 style="text-align: center;">{{ message }}</h3>
            {% endfor %}
        {% endif %}
    </div>

    <div class="signup-content">
        <h2 class="form-title">Create Profile Form</h2>
        <h3>Your Username: {{ request.user.username }}</h3>
        <form method="POST" id="profileForm" class="signup-form" data-cities-url="{% url 'users:ajax_load_cities' %}" novalidate  enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-input" name="first_name" id="first_name" placeholder="Enter Your First Name" required/>
            </div>
            <div class="form-group">
                <input type="text" class="form-input" name="last_name" id="last_name" placeholder="Enter Your Surname" required/>
            </div>
            <div class="select_option">
                <span class="select-wrapper">
                    <select name="gender">
                        <option value="*" disabled selected>Gender</option>
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                    </select>
                </span>
            </div>
            <div class="form-group">
                <input type="text" class="form-input" name="date_of_birth" id="date_of_birth" placeholder="FORMAT: YYYY-MM-DD" required/>
            </div>
        </form>
    </div>
{% endblock content %}


{% block javascript %}
{% endblock javascript %}

users/templates/users/create_profile_copy.html
{% extends 'users/base.html' %}
{% load static %}
{% block title %}Create Profile Form{% endblock title %}

{% block content %}
    <div class="message">
        {% if messages %}
            {% for message in messages %}
                <h3 style="text-align: center;">{{ message }}</h3>
            {% endfor %}
        {% endif %}
    </div>

    <div class="signup-content">
        <h2 class="form-title">Create Profile Form</h2>
        <h3>Your Username: {{ request.user.username }}</h3>
        <form method="post" id="profileForm" data-cities-url="{% url 'users:ajax_load_cities' %}" novalidate  enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <div class="form-group">
                <input type="submit" name="submit" id="submit" class="form-submit" value="Save Profile"/>
            </div>
        </form>
    </div>
{% endblock content %}

{% block javascript %}
    <script src="{% static 'js/create_profile.js' %}"></script>
{% endblock javascript %}

users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Form</title>
</head>
<body>
    <div>
        <h2>Login Form</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Login">
        </form>
    </div>
    <div>
        <p>Don't have an account?</p>
        <button><a href="{% url 'users:signup' %}">Sign Up</a></button>
    </div>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block title %}Login Form{% endblock title %}

{% block content %}
    <div class="message">
        {% if messages %}
            {% for message in messages %}
                <h3 style="text-align: center; background: green;">{{ message }}</h3>
            {% endfor %}
        {% endif %}
    </div>
    <div class="signup-content">
        <form method="POST" id="signup-form" class="signup-form">
            {% csrf_token %}
            <h2 class="form-title">Login Form</h2>
            <div class="form-group">
                <input type="text" class="form-input" name="username" id="username" placeholder="Your Username" required/>
            </div>
            <div class="form-group">
                <input type="password" class="form-input" name="password" id="password" placeholder="Your Password" required/>
                <span class="field-icon" onclick="showPassword()">
                    <i class="far fa-eye-slash"></i>
                </span>
            </div>

            <div class="form-group">
                <input type="submit" name="submit" id="submit" class="form-submit" value="Login"/>
            </div>
        </form>
        <p class="loginhere">
            Don't have an account ? <a href="{% url 'users:signup' %}" class="loginhere-link">Sign Up Here</a>
        </p>
    </div>
{% endblock content %}

users/templates/users/signup.html
{% extends 'users/base.html' %}

{% block title %}Sign Up Form{% endblock title %}

{% block content %}
    <div class="message">
        {% if messages %}
            {% for message in messages %}
                <h3 style="text-align: center;">{{ message }}</h3>
            {% endfor %}
        {% endif %}
    </div>

    <div class="signup-content">
        <form method="POST" id="signup-form" class="signup-form">
            {% csrf_token %}
            <h2 class="form-title">Sign Up Form</h2>
            <div class="form-group">
                <input type="text" class="form-input" name="username" id="username" placeholder="Enter Your Username" required/>
            </div>

            <div class="form-group">
                <input type="email" class="form-input" name="email" id="email" placeholder="Enter Your Email" required/>
            </div>

            <div class="form-group">
                <input type="password" class="form-input" name="password" id="password" placeholder="Enter Your Password" required/>
                <span class="field-icon" onclick="showPassword()">
                    <i class="far fa-eye-slash"></i>
                </span>
            </div>

            <div class="form-group">
                <input type="password" class="form-input" name="re_password" id="re_password" placeholder="Repeat your password" required/>
                <span class="field-icon" onclick="showPassword2()">
                    <i class="far fa-eye-slash"></i>
                </span>
            </div>

            <div class="form-group">
                <input type="submit" name="submit" id="submit" class="form-submit" value="Sign Up"/>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/signup_copy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up Form</title>
</head>
<body>
    <div>
        <h2>Sign Up Form</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sign Up">
        </form>
    </div>
</body>
</html>

users/templates/users/user_created.html
{% extends 'users/base.html' %}
{% block title %}Create Profile Form{% endblock title %}

{% block content %}
    <div class="signup-content">
        <h2 class="form-title">Your profile was created successfully...</h2>
        <button class="form-submit"><a href="{% url 'chat:home' %}">Go To Chat Page</a></button>
    </div>
{% endblock content %}